project:
  type: website
  output-dir: docs

website:
  title: "View Related Posts"
  navbar:
    background: primary
    left: 
      - "Carlos Saint-Preux"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css

editor: visual

